import type { Metadata } from 'next';

import './globals.css';
import { Header } from '@/components/ui/layouts/Header';
import { Footer } from '@/components/ui/layouts/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ja'>
      <body className='bg-teal-600'>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
